"""Updating column name for Roles

Revision ID: b97701202f2b
Revises: 2adf501c008b
Create Date: 2025-10-07 15:44:24.718902

"""

# revision identifiers, used by Alembic.
revision = "b97701202f2b"
down_revision = "2adf501c008b"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE custom_roles RENAME TO customroles")
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE customroles RENAME TO custom_roles")
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
